### ISSUE TITLE
Opens Incognito

### ISSUE THREAD

**Issue by harryaldwithjarryald** [AshtonDavies/bookmarklet-executor#2]
it opens the incognito thing for me when i try to open it not the bookmarklet executor is this still being worked on?

**Comment by AshtonDavies** [comment]
Incognito is an extra feature.

**Comment by jarryharry456** [comment]
How do i get bookmarklet exec to work then?  It says I have to login before I can use the internet to go on anything?  
Thanks for replying so fast

**Comment by AshtonDavies** [comment]
Instructions [here](https://github.com/3kh0/ext-remover/discussions/845#discussioncomment-7826739).

**Comment by jarryharry456** [comment]
What do I do if .adguard-dns.com is blocked

**Comment by AshtonDavies** [comment]
> What do I do if .adguard-dns.com is blocked

Assuming this is an extension filter, it's easiest to spam the file urls switch in extension settings while loading the IP linker.

**Comment by jarryharry456** [comment]
What if I have hapara filter AND Cisco trying to block it

**Comment by AshtonDavies** [comment]
Spam both in split screen. If you are unable to do that, you can try an exploit from [here](https://chrose.netlify.app). Some may not work depending on the extension you are bypassing. Technically you could just visit the page from a phone or other device on the same network and that would work.

**Comment by jarryharry456** [comment]
I got to the link but now it says chromewebstore.google.com does not provide a private connection so I can’t go on the website

**Comment by AshtonDavies** [comment]
Perfect, now type "thisisunsafe" on that screen and it should proceed. That's usual behavior for DNS spoofing.

**Comment by jarryharry456** [comment]
Oh ok i didn’t know that trick to bypass it

**Comment by jarryharry456** [comment]
Now it says the bookmarklets aren’t compatible with this webstore version

**Comment by jarryharry456** [comment]
How would I fix that

**Comment by AshtonDavies** [comment]
I'm not familiar with that message. Could you provide a screenshot?

**Comment by jarryharry456** [comment]
![IMG_4336](https://github.com/AshtonDavies/bookmarklet-executor/assets/148587892/ab21af69-882c-4677-9ad5-698d00a9b382)
![IMG_4335](https://github.com/AshtonDavies/bookmarklet-executor/assets/148587892/348ae87e-3c45-46b4-ad3d-83d1868f4fdf)

**Comment by AshtonDavies** [comment]
Oh yeah. Those require versions of Chrome OS below 106, which used the old webstore. You might not be able to spoof it on the old one, because it loads the executor through Kproxy with it's site folders. There's no web server for this DNS, so we might not be able to use those for anyone below v106. Same problem goes for the side panel execution idea.

**Comment by jarryharry456** [comment]
Also pressing redirect brings me to chrome.google.com/webstorex that just gives me a 404 error (not a Google one)

**Comment by AshtonDavies** [comment]
Oh yeah. Those require versions of Chrome OS below 106, which used the old webstore. You might not be able to spoof it on the old one, because it loads the executor through Kproxy with it's site folders. There's no web server for this DNS, so we might not be able to use those for anyone below v106. Same problem goes for the side panel execution idea.

**Comment by jarryharry456** [comment]
So there is no way for me to disable extensions using this dns on the latest chromeos

**Comment by AshtonDavies** [comment]
> So there is no way for me to disable extensions using this dns on the latest chromeos 

LTBEEF is patched in v106 and above.

**Comment by jarryharry456** [comment]
So what can I use this for?  Or is it still just a work in progress?

**Comment by AshtonDavies** [comment]
If you're on the latest version and have the webstore blocked, you can use Extension Launcher. I have [another server](https://linkip.adguard-dns.com/linkip/d4cfbd43/MrXXtcXx4U4QvPOyloGK4Y3gdER6FjJrYAiHdQoehux) that you can link to if you want to block filtering extensions. I have tested and fully blocked Lightspeed Filter Agent and Hapara Highlights with it. It also freezes policies and updates. If you are going to link to it, please be somewhat conservative of requests. There's a 300K total max for everyone.

**Comment by Convextocode** [comment]
oh ok.  What do you mean by blocked?  It is blocked for me for most extensions but some work.

**Comment by AshtonDavies** [comment]
> oh ok.  What do you mean by blocked?  It is blocked for me for most extensions but some work.
> 

Filtering extensions send requests to servers to determine site block states or to send statistics. With a DNS, I can check in the query log to see what domains they connect to while they're running and block those domains. After that, the extensions can only rely on their cached data to do their job, which can be cleared if you know how to do that.

I haven't had installed and fiddled with extensions other than Lightspeed Filter Agent and Hapara Highlights, so that's why most extensions aren't blocked.
